@files = (
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="ESXCreateConfigForm"]/value', 'ESXCreateConfigForm.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="ESXEditConfigForm"]/value',   'ESXEditConfigForm.xml'],

    ['//property[propertyName="preamble"]/value', 'preamble.pl'],
    ['//property[propertyName="ESX"]/value',      'ESX.pm'],

    ['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateConfiguration"]/command',       'conf/createcfg.pl'],
    ['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateAndAttachCredential"]/command', 'conf/createAndAttachCredential.pl'],
    ['//procedure[procedureName="DeleteConfiguration"]/step[stepName="DeleteConfiguration"]/command',       'conf/deletecfg.pl'],

    ['//procedure[procedureName="Create"]/step[stepName="Create"]/command',                             'vm/create.pl'],
    ['//procedure[procedureName="Clone"]/step[stepName="Clone"]/command',                               'vm/clone.pl'],
    ['//procedure[procedureName="Relocate"]/step[stepName="Relocate"]/command',                         'vm/relocate.pl'],
    ['//procedure[procedureName="Cleanup"]/step[stepName="Cleanup"]/command',                           'vm/cleanup.pl'],
    ['//procedure[procedureName="Revert"]/step[stepName="Revert"]/command',                             'vm/revert.pl'],
    ['//procedure[procedureName="Snapshot"]/step[stepName="Snapshot"]/command',                         'vm/snapshot.pl'],
    ['//procedure[procedureName="PowerOn"]/step[stepName="PowerOn"]/command',                           'vm/poweron.pl'],
    ['//procedure[procedureName="PowerOff"]/step[stepName="PowerOff"]/command',                         'vm/poweroff.pl'],
    ['//procedure[procedureName="Shutdown"]/step[stepName="Shutdown"]/command',                         'vm/shutdown.pl'],
    ['//procedure[procedureName="Suspend"]/step[stepName="Suspend"]/command',                           'vm/suspend.pl'],
    ['//procedure[procedureName="CreateResourceFromVM"]/step[stepName="CreateResourceFromVM"]/command', 'vm/createresourcefromvm.pl'],
    ['//procedure[procedureName="GetVMConfiguration"]/step[stepName="GetVMConfiguration"]/command',     'vm/getvmconfiguration.pl'],
    ['//procedure[procedureName="Import"]/step[stepName="Import"]/command',                             'vm/import.pl'],
    ['//procedure[procedureName="Export"]/step[stepName="Export"]/command',                             'vm/export.pl'],
    ['//procedure[procedureName="RegisterVM"]/step[stepName="RegisterVM"]/command',                     'vm/registervm.pl'],
    ['//procedure[procedureName="CloudManagerGrow"]/step[stepName="grow"]/command',                     'vm/step.grow.pl'],
    ['//procedure[procedureName="CloudManagerShrink"]/step[stepName="shrink"]/command',                 'vm/step.shrink.pl'],

    ['//procedure[procedureName="Create"]/step[stepName="SetTimelimit"]/command',               'setTimelimit.pl'],
    ['//procedure[procedureName="Clone"]/step[stepName="SetTimelimit"]/command',                'setTimelimit.pl'],
    ['//procedure[procedureName="Relocate"]/step[stepName="SetTimelimit"]/command',             'setTimelimit.pl'],
    ['//procedure[procedureName="Cleanup"]/step[stepName="SetTimelimit"]/command',              'setTimelimit.pl'],
    ['//procedure[procedureName="Revert"]/step[stepName="SetTimelimit"]/command',               'setTimelimit.pl'],
    ['//procedure[procedureName="Snapshot"]/step[stepName="SetTimelimit"]/command',             'setTimelimit.pl'],
    ['//procedure[procedureName="PowerOn"]/step[stepName="SetTimelimit"]/command',              'setTimelimit.pl'],
    ['//procedure[procedureName="PowerOff"]/step[stepName="SetTimelimit"]/command',             'setTimelimit.pl'],
    ['//procedure[procedureName="Shutdown"]/step[stepName="SetTimelimit"]/command',             'setTimelimit.pl'],
    ['//procedure[procedureName="Suspend"]/step[stepName="SetTimelimit"]/command',              'setTimelimit.pl'],
    ['//procedure[procedureName="CreateResourceFromVM"]/step[stepName="SetTimelimit"]/command', 'setTimelimit.pl'],
    ['//procedure[procedureName="GetVMConfiguration"]/step[stepName="SetTimelimit"]/command',   'setTimelimit.pl'],
    ['//procedure[procedureName="Import"]/step[stepName="SetTimelimit"]/command',               'setTimelimit.pl'],
    ['//procedure[procedureName="Export"]/step[stepName="SetTimelimit"]/command',               'setTimelimit.pl'],
    ['//procedure[procedureName="RegisterVM"]/step[stepName="SetTimelimit"]/command',           'setTimelimit.pl'],

    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Create"]/value',               'ui_forms/create.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Clone"]/value',                'ui_forms/clone.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Cleanup"]/value',              'ui_forms/cleanup.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Relocate"]/value',             'ui_forms/relocate.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Revert"]/value',               'ui_forms/revert.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Snapshot"]/value',             'ui_forms/snapshot.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="PowerOn"]/value',              'ui_forms/poweron.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="PowerOff"]/value',             'ui_forms/poweroff.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Shutdown"]/value',             'ui_forms/shutdown.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Suspend"]/value',              'ui_forms/suspend.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="CreateResourceFromVM"]/value', 'ui_forms/createresourcefromvm.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="GetVMConfiguration"]/value',   'ui_forms/getvmconfiguration.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Import"]/value',               'ui_forms/import.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="Export"]/value',               'ui_forms/export.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="RegisterVM"]/value',           'ui_forms/registervm.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="CloudManagerShrink"]/value',   'ui_forms/cloudmanagershrink.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="CloudManagerGrow"]/value',     'ui_forms/cloudmanagergrow.xml'],

    ['//property[propertyName="ec_setup"]/value', 'ec_setup.pl'],
         );
