@files = (
 ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="ESXCreateConfigForm"]/value'  , 'ESXCreateConfigForm.xml'],
 ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="ESXEditConfigForm"]/value'  , 'ESXEditConfigForm.xml'],

 ['//property[propertyName="preamble"]/value' , 'preamble.pl'],
 ['//property[propertyName="ESX"]/value' , 'ESX.pm'],
 
 ['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateConfiguration"]/command' , 'conf/createcfg.pl'],
 ['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateAndAttachCredential"]/command' , 'conf/createAndAttachCredential.pl'],
 ['//procedure[procedureName="DeleteConfiguration"]/step[stepName="DeleteConfiguration"]/command' , 'conf/deletecfg.pl'],
 
 ['//procedure[procedureName="Create"]/step[stepName="Create"]/command' , 'vm/create.pl'],
 ['//procedure[procedureName="Clone"]/step[stepName="Clone"]/command' , 'vm/clone.pl'],
 ['//procedure[procedureName="Relocate"]/step[stepName="Relocate"]/command' , 'vm/relocate.pl'],
 ['//procedure[procedureName="Cleanup"]/step[stepName="Cleanup"]/command' , 'vm/cleanup.pl'],
 ['//procedure[procedureName="Revert"]/step[stepName="Revert"]/command' , 'vm/revert.pl'],
 ['//procedure[procedureName="Snapshot"]/step[stepName="Snapshot"]/command' , 'vm/snapshot.pl'],
 ['//procedure[procedureName="PowerOn"]/step[stepName="PowerOn"]/command' , 'vm/poweron.pl'],
 ['//procedure[procedureName="PowerOff"]/step[stepName="PowerOff"]/command' , 'vm/poweroff.pl'],
 ['//procedure[procedureName="Shutdown"]/step[stepName="Shutdown"]/command' , 'vm/shutdown.pl'],
 ['//procedure[procedureName="Suspend"]/step[stepName="Suspend"]/command' , 'vm/suspend.pl'],
 ['//procedure[procedureName="CreateResourceFromVM"]/step[stepName="CreateResourceFromVM"]/command' , 'vm/createresourcefromvm.pl'],
 ['//procedure[procedureName="GetVMConfiguration"]/step[stepName="GetVMConfiguration"]/command' , 'vm/getvmconfiguration.pl'],
 ['//procedure[procedureName="Import"]/step[stepName="Import"]/command' , 'vm/import.pl'],
 ['//procedure[procedureName="Export"]/step[stepName="Export"]/command' , 'vm/export.pl'],
 ['//procedure[procedureName="RegisterVM"]/step[stepName="RegisterVM"]/command' , 'vm/registervm.pl'],
 
 ['//procedure[procedureName="Create"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Clone"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Relocate"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Cleanup"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Revert"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Snapshot"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="PowerOn"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="PowerOff"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Shutdown"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Suspend"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="CreateResourceFromVM"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="GetVMConfiguration"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Import"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Export"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="RegisterVM"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],

 ['//property[propertyName="ec_setup"]/value', 'ec_setup.pl'],
);
